logging:
  level:
    ss.parser: DEBUG

server:
  address: 127.0.0.1

spring:
  security:
    user:
      name: admin
      password: admin

  mail:
    host: localhost
    protocol: smtps
    port: 465
    username: user@localhost
    password: secret

ss-parser:
  scheduler:
    parallel: true
    randomize: false

  mail:
    enabled: false
    rate: 1h
    working-hours:
      start: "00:00"
      end: "23:59"
    max-message-size: 100000
    from: user@localhost
    to: user@localhost
    subject: Новые объекты, отвечающие вашему поиску SS.COM

  telegram:
    enabled: false
    rate: 1h
    working-hours:
      start: "00:00"
      end: "23:59"
    max-message-size: 4096
    bot-token: "0000000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    chat-id: "0"
    timeout: 10s

  car:
    enabled: false
    rate: 10m
    url: https://www.ss.com/ru/transport/cars/sell/rss/
    timeout: 10s
    regex: "(?s:(Марка: (<b>)+(?<mark>[^<]+)<br>(?<model>[^<]+)(</b>)+<br/>.*?)?Год: (<b>)+(?<year>\\d+)(</b>)+<br/>.*?(Объём: (<b>)+(?<engine>[^<]+)(</b>)+<br/>.*?)?(Пробег: (<b>)+(?<run>\\d+)(</b>)? тыс.</b><br/>.*?)?Цена: (<b>)+(?<price>[\\d,]+))(</b>)?  €"
    replace: "Марка: <b>${mark}</b><br/>Модель: <b>${model}</b><br/>Год: <b>${year}</b><br/>Двигатель: <b>${engine}</b><br/>Пробег: <b>${run} тыс.</b><br/>Цена: <b>${price} €</b>"
    expression: true

  flat-sell:
    enabled: false
    rate: 10m
    url: https://www.ss.com/ru/real-estate/flats/riga/sell/rss/
    timeout: 10s
    regex: "(?s:Район: (<b>)+(?<region>[^<]+)<br>(?<address>[^<]+)(</b>)+<br/>.*?(К\\.: (<b>)+(?<rooms>\\d+)(</b>)+<br/>)?м²: (<b>)+(?<area>\\d+)(</b>)+<br/>Этаж: (<b>)+(?<floor>-?\\d+)/(?<floors>-?\\d+)(</b>)+<br/>Серия: (<b>)+(?<series>[^<]+)(</b>)+<br/>: (<b>)+(?<ppm2>[\\d,.]+)(</b>)* €(</b>)*<br/>Цена: (<b>)+(?<price>[\\d,]+)(</b>)*  €)"
    replace: "Район: <b>${region}</b><br/>Адрес: <b>${address}</b><br/>Комнат: <b>${rooms}</b><br/>Площадь: <b>${area} м²</b><br/>Этаж: <b>${floor}/${floors}</b><br/>Серия: <b>${series}</b><br/>Цена за м²: <b>${ppm2} €</b><br/>Цена: <b>${price} €</b>"
    expression: true

  flat-rent:
    enabled: false
    rate: 10m
    url: https://www.ss.com/ru/real-estate/flats/riga/hand_over/rss/
    timeout: 10s
    regex: "(?s:Район: (<b>)+(?<region>[^<]+)<br>(?<address>[^<]+)(</b>)+<br/>.*?(К\\.: (<b>)+(?<rooms>\\d+)(</b>)+<br/>)?м²: (<b>)+(?<area>\\d+)(</b>)+<br/>Этаж: (<b>)+(?<floor>-?\\d+)/(?<floors>-?\\d+)(</b>)+<br/>Серия: (<b>)+(?<series>[^<]+)(</b>)+<br/>: (<b>)+(?<ppm2>[\\d,.]+)(</b>)* €(</b>)*<br/>Цена: (<b>)+(?<price>[\\d,]+)(</b>)*  €)"
    replace: "Район: <b>${region}</b><br/>Адрес: <b>${address}</b><br/>Комнат: <b>${rooms}</b><br/>Площадь: <b>${area} м²</b><br/>Этаж: <b>${floor}/${floors}</b><br/>Серия: <b>${series}</b><br/>Цена за м²: <b>${ppm2} €</b><br/>Цена: <b>${price} €</b>"
    expression: true

  home:
    enabled: false
    rate: 10m
    url: https://www.ss.com/ru/real-estate/homes-summer-residences/riga/sell/rss/
    timeout: 10s
    regex: "(?s:Район: (<b>)+(?<region>[^<]+)<br>(?<address>[^<]+)(</b>)+<br/>.*?м²: (<b>)+(?<area>[\\d,]+)(</b>)+<br/>Этажей: (<b>)+(?<floors>\\d+)(</b>)+<br/>Пл\\. зем\\.: (<b>)+(?<land>[\\d,.]+)( (?<unit>м²|га\\.))?(</b>)+<br/>Цена: (<b>)+(?<price>[\\d,]+)(</b>)*  €)"
    replace: "Район: <b>${region}</b><br/>Адрес: <b>${address}</b><br/>Площадь: <b>${area} м²</b><br/>Этажей: <b>${floors}</b><br/>Площадь земли: <b>${land} ${unit}</b><br/>Цена: <b>${price} €</b>"
    expression: true
